---
name: eliud_pkg_workflow
description: eliud_pkg_workflow is a package to provide workflows (a number of actions)
  to your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_workflow
version: 1.1.5+5
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core: ^1.1.5+7
  eliud_pkg_notifications: ^1.1.5+5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  flutter:
    sdk: flutter
dependency_overrides:   
  eliud_core: 
    path: ../eliud_core
  eliud_core_model: 
    path: ../eliud_core_model
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
