---
name: eliud_pkg_workflow
description: eliud_pkg_workflow is a package to provide workflows (a number of actions)
  to your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_workflow
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_pkg_workflow_model: ^1.3.0
  eliud_core_main: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_model: ^1.3.0
  eliud_pkg_notifications: ^1.3.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  eliud_core: ^1.3.0
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
  lints: ^5.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
