---
name: eliud_pkg_workflow
description: eliud_pkg_workflow is a package to provide workflows (a number of actions)
  to your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_workflow
version: 1.1.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_pkg_workflow_model:                                                                          # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow_model

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
