---
name: "eliud_pkg_workflow"
description: "Eliud package for workflow, actions"
homepage: "https://eliud.io"
repository: "https://github.com/eliudio/eliud_pkg_workflow"
version: "1.0.1+3"
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: "flutter"
  eliud_core: "1.0.4+8"
  eliud_pkg_notifications: "^1.0.1+1"
  bloc: "^8.1.0"
  cloud_firestore: "^4.6.0"
  collection: "^1.17.0"
  datetime_picker_formfield: "^2.0.0"
  equatable: "^2.0.5"
  flutter_bloc: "^8.1.2"
  http: "^0.13.5"
  intl: "^0.18.1"
  meta: "^1.8.0"
dev_dependencies:
  build_runner: "^2.4.6"
  eliud_generator: "1.0.4+1"
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
