name: eliud_pkg_workflow
description: Eliud package for workflow, actions
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud

version: 1.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core: ^1.0.4
  eliud_pkg_notifications: ^1.0.1

dev_dependencies:
  build_runner: ^2.1.0

  eliud_generator: ^1.0.3

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
